import './globals.css'
import TankstackProvider from '@/providers/TanstackProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <TankstackProvider>
        <body suppressHydrationWarning={true}>
          {children}
        </body>
      </TankstackProvider>
      
    </html>
  )
}
