export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  )
}
